IMDB/ViewModels/MovieProfileViewModel.cs
using IMDB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IMDB.ViewModels
{
    public class MovieProfileViewModel
    {
        public Movie Movie { get; set; }

        public IEnumerable<Actor> Actors { get; set; }

        public IEnumerable<MovieActor> MovieActor { get; set; }

        public Director Director { get; set; }

        public Comment Comment { get; set; }

        public IEnumerable<Comment> Comments { get; set; }

        public User User { get; set; }

        public Like Like { get; set; }

        public IEnumerable<Like> Likes { get; set; }

        public int Counter { get; set; }

        public string UserName { get; set; }
    }
}

IMDB/Controllers/ViewController.cs
using IMDB.Classes;
using IMDB.Models;
using IMDB.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMDB.Controllers
{
    public class ViewController : Controller
    {
        private DBContext db = new DBContext();
        Find search = new Find();
         // random user to be replaced later

        // GET: View
        public ActionResult ActorProfile(int id)
        {
            MovieActor particpations = new MovieActor();
            var actorView = search.FindActorByID(id);
            var actor_movie = search.FindMovieActorsByID(id).ToList();
            Actor_Movie actorProfile = new Actor_Movie
            {
                Actor = actorView,
                MovieActors = actor_movie

            };
            if (actorProfile == null)
                return HttpNotFound();

            return View(actorProfile);
        }


        public ActionResult DirectorProfile(int id)
        {

            var directorView = search.FindDirectorByID(id);
            var director_movie = search.FindMovieDirectorsByID(id).ToList();
            Director_Movie directorProfile = new Director_Movie
            {
                Director = directorView,
                Movies = director_movie

            };
            if (directorProfile == null)
                return HttpNotFound();

            return View(directorProfile);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult MovieProfile(int id)
        {
            var movie = search.FindMovieByID(id);
            if (movie == null)
                return HttpNotFound();

            Session["MovieId"] = id;
            var userName = " ";
            if (Session["UserName"] != null)
            {
                userName = Session["UserName"].ToString();
            }
            var movieActors = db.MovieActors.ToList().Where(model => model.MovieID == id);
            var comments = db.Comments.Where(model => model.MovieID == id);
            var director = movie.Director;
            var rateCount = db.Likes.Where(model => model.LikeValue == true && model.MovieID == id);
            MovieProfileViewModel profile = new MovieProfileViewModel()
            {
                Movie = movie,
                MovieActor = movieActors,
                Director = director,
                Comments = comments,
                UserName = userName,
                Counter = rateCount.Count()
            };
            
            return View(profile);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MovieProfile(MovieProfileViewModel profile,int? liked)
        {
            int userID = (int)Session["UserId"];
            var movieId = Int32.Parse(Session["MovieId"].ToString());
            var alreadyLiked = db.Likes.SingleOrDefault(model => model.UserID == userID && model.MovieID == movieId);

            if (liked != null)
            {
                Boolean likeValue = false;
                if (liked == 1)
                {
                    likeValue = true;
                }
                if (alreadyLiked == null)
                {
                    Like like = new Like() {
                    MovieID = movieId,
                    UserID = userID,
                    LikeValue = likeValue
                    };
                    db.Likes.Add(like);
                }
                else
                {
                    Like like = db.Likes.SingleOrDefault(model => model.UserID == userID && model.MovieID == movieId); // to get Like ID for update

                    like.MovieID = movieId;
                    like.UserID = userID;
                    like.LikeValue = likeValue;
                };
            }

            if (profile.Comment != null)
            {
                profile.Comment.MovieID = movieId;
                profile.Comment.UserID = userID;
                db.Comments.Add(profile.Comment);
                
            }
            db.SaveChanges();
            return RedirectToAction("MovieProfile");
        }
    }
}

IMDB/Views/View/ActorProfile.cshtml
@model IMDB.ViewModels.Actor_Movie
@using IMDB.Models
@{
    ViewData["Title"] = "Actor Details";
}
<!DOCTYPE html>
<html>
<head>
    <title>Portfolio website</title>
    <link rel="stylesheet" type="text/css" href="~/Content/ActorStyle.css">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <header>

        @Html.ActionLink("IMDb", "Home", new { controller = "Home" }, new { @class = "logo" })

        <ul class="navbar">

            <li>
                @Html.ActionLink("Home", "Home", new { controller = "Home" }, new { @class = "home_active" })
            </li>

            <li>@Html.ActionLink("Search", "Searching", new { controller = "Search" })</li>

        </ul>
        @Html.ActionLink("Sign In", "Login", new { controller = "User" }, new { @class = "btn" })

    </header>
    <!----hero Section start---->
    <!----About section start---->
    <section class="about">
        <div class="main">
            @if (Model.Actor.ActorIMG != null)
            {
                <img style="width:200px;height:100%;border-radius:7.2%" src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(Model.Actor.ActorIMG))" alt="@Model.Actor.FirstName @Model.Actor.LastName">
            }
            else
            {
                <img style="width:200px;height:100%;border-radius:7.2%" src="~/Image/DefaultProfile.jpg" . alt="@Model.Actor.FirstName @Model.Actor.LastName" />
            }

            <div class="about-text">
                <h2>@Html.DisplayFor(model => model.Actor.FirstName) @Html.DisplayFor(model => model.Actor.LastName)</h2>
                <h5>Actor <span>& Director</span></h5>
                <p>@Html.DisplayFor(model => model.Actor.Description)</p>
                <form class="rating">
                    <label>
                        <input type="radio" name="stars" value="1" />
                        <span class="icon">★</span>
                    </label>
                    <label>
                        <input type="radio" name="stars" value="2" />
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                    </label>
                    <label>
                        <input type="radio" name="stars" value="3" />
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                    </label>
                    <label>
                        <input type="radio" name="stars" value="4" />
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                    </label>
                    <label>
                        <input type="radio" name="stars" value="5" />
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                    </label>
                </form>
            </div>
        </div>
    </section>


    <div class="service">
        <div class="title">
            <h2>Movies</h2>
        </div>
        <div class="box">
            @foreach (var item in Model.MovieActors)
            {
                <div class="card">
                    <div class="content">
                        <a href="" target="_blank">
                            @if (item.Movie.MovieIMG != null)
                            {
                                <img src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(item.Movie.MovieIMG))" alt="@item.Movie.MovieName" id="movieImage" />
                            }
                            else
                            {
                                <img src="~/Image/MovieImages/MovieDefault.jpg" alt="@item.Movie.MovieName" />
                            }
                            <div class="content-overlay"></div>
                            <div class="content-details fadeIn-bottom">
                                <h3 class="content-title">Go to movie</h3>
                                <p class="content-text"> @Html.DisplayFor(model => item.Movie.Description)</p>
                            </div>
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>


    <!------footer start--------->
    <footer>
        <div class="social">
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-dribbble"></i></a>
        </div>

    </footer>
</body>
</html>

IMDB/Views/View/DirectorProfile.cshtml
@model IMDB.ViewModels.Director_Movie
@using IMDB.Models


@{
    ViewData["Title"] = "Director Details";
}
<!DOCTYPE html>
<html>
<head>
    <title>Portfolio website</title>
    <link rel="stylesheet" type="text/css" href="~/Content/ActorStyle.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <header>

        @Html.ActionLink("IMDb", "Home", new { controller = "Home" }, new { @class = "logo" })

        <ul class="navbar">

            <li>
                @Html.ActionLink("Home", "Home", new { controller = "Home" }, new { @class = "home_active" })
            </li>

            <li>@Html.ActionLink("Search", "Searching", new { controller = "Search" })</li>

        </ul>
        @Html.ActionLink("Sign In", "Login", new { controller = "User" }, new { @class = "btn" })

    </header>

    <section class="about">
        <div class="main">
            @if (Model.Director.DirectorIMG != null)
            {
                <img style="width:200px;height:100%;border-radius:7.2%" src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(Model.Director.DirectorIMG))" alt="@Model.Director.FirstName @Model.Director.LastName">
            }
            else
            {
                <img style="width:200px;height:100%;border-radius:7.2%" src="~/Image/DefaultProfile.jpg" . alt="@Model.Director.FirstName @Model.Director.LastName" />
            }
            <div class="about-text">
                <h2>@Html.DisplayFor(model => model.Director.FirstName) @Html.DisplayFor(model => model.Director.LastName)</h2>
                <h5>Actor <span>& Director</span></h5>
                <p>@Html.DisplayFor(model => model.Director.Description)</p>
                <form class="rating">
                    <label>
                        <input type="radio" name="stars" value="1" />
                        <span class="icon">★</span>
                    </label>
                    <label>
                        <input type="radio" name="stars" value="2" />
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                    </label>
                    <label>
                        <input type="radio" name="stars" value="3" />
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                    </label>
                    <label>
                        <input type="radio" name="stars" value="4" />
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                    </label>
                    <label>
                        <input type="radio" name="stars" value="5" />
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                        <span class="icon">★</span>
                    </label>
                </form>
            </div>
        </div>
    </section>


    <div class="service">
        <div class="title">
            <h2>Movies</h2>
        </div>
        <div class="box">
            @foreach (var item in Model.Movies)
            {
                <div class="card">
                    <div class="content">
                        <a href="" target="_blank">

                            @if (item.MovieIMG != null)
                            {
                                <img src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(item.MovieIMG))" alt="@item.MovieName" id="movieImage" />
                            }
                            else
                            {
                                <img src="~/Image/MovieImages/MovieDefault.jpg" alt="@item.MovieName" />
                            }

                            <div class="content-overlay"></div>
                            <div class="content-details fadeIn-bottom">
                                <h3 class="content-title">Go to movie</h3>
                                <p class="content-text"> @Html.DisplayFor(model => item.Description)</p>
                            </div>
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>




    <!------footer start--------->
    <footer>
        <div class="social">
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-dribbble"></i></a>
        </div>

    </footer>
</body>
</html>

IMDB/Views/View/MovieProfile.cshtml
@model IMDB.ViewModels.MovieProfileViewModel
@{
    ViewData["Title"] = "Movie Details";
}
<!DOCTYPE html>
<html>
<head>
    <title>Movie Profile</title>
    <link rel="stylesheet" type="text/css" href="~/Content/ActorStyle.css">
    <link href="~/Content/MovieProfile.css" rel="stylesheet" />
    <link href="~/Content/Comment.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <header>

        @Html.ActionLink("IMDb", "Home", new { controller = "Home" }, new { @class = "logo" })

        <ul class="navbar">

            <li>
                @Html.ActionLink("Home", "Home", new { controller = "Home" }, new { @class = "home_active" })
            </li>

            <li>@Html.ActionLink("Search", "Searching", new { controller = "Search" })</li>

        </ul>
        @if (Model.UserName != " ")
        {
            <span style="padding:8px">@Html.DisplayFor(model => model.UserName)</span>
        }
        else
        {
            @Html.ActionLink("Sign In", "Login", new { controller = "User" }, new { @class = "btn" })
        }

    </header>

    <section class="about">
        <div>
            <div class="main">
                @if (Model.Movie.MovieIMG != null)
                {
                    <img src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(Model.Movie.MovieIMG))" alt="@Model.Movie.MovieName" id="movieImage" />
                }
                else
                {
                    <img src="~/Image/MovieImages/MovieDefault.jpg" alt="@Model.Movie.MovieName" />
                }

                <div class="about-text">
                    <h2>@Html.DisplayFor(model => model.Movie.MovieName)</h2>
                    <hr />
                    <p>@Html.DisplayFor(model => model.Movie.Description)</p>

                    <h4>Actors</h4>
                    <hr />
                    <div class="text-line">
                        @foreach (var item in Model.MovieActor)
                        {

                            @Html.ActionLink(item.Actor.FirstName + " " + item.Actor.LastName, "ActorProfile", new { id = item.ActorID }, new { @class = "text-info" })
                            <span>, </span>

                        }
                    </div>
                    <br />
                    <br />
                    <h4>Director</h4>
                    <hr />
                    <div class="text-line">
                        @if (Model.Director == null)
                        {
                            <span>Null</span>
                        }
                        else
                        {
                            @Html.ActionLink(Model.Director.FirstName + " " + Model.Director.LastName, "DirectorProfile", new { id = Model.Director.DirectorID }, new { @class = "text-info" })
                        }
                    </div>
                </div>
            </div>
            @using (Html.BeginForm("MovieProfile", "View", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="Likes">
                    @if ( Model.UserName != " " )
                    {
                    <button class=" like" value="1" name="liked"></button>
                    <button class=" dislike" value="0" name="liked"></button>
                    }
                    <span style="position:absolute;margin-top:20px;margin-left:30px;">
                        @Html.DisplayFor(model => model.Counter)
                        Likes
                    </span>
                </div>
            }
        </div>
    </section>


    <section class="content-item" id="comments">
        <div class="container">
            <br />
            <div class="row">
                <div class="col-sm-8">
                    <div class="comment">
                        @using (Html.BeginForm("MovieProfile", "View", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            if (Model.UserName != " ")
                            {
                            <h3 class="pull-left">New Comment</h3>

                                <fieldset>
                                    <div class="row">
                                        <div class="form-group col-xs-12 col-sm-9 col-lg-10">
                                            @Html.TextAreaFor(model => model.Comment.Content)
                                        </div>
                                    </div>
                                </fieldset>
                                <input type="submit" value="Submit" class="btn btn-normal pull-right" style="cursor:pointer;">
                                <br />
                            }
                                <div class="media">
                                    @foreach (var item in Model.Comments)
                                    {
                                        if (item.User.ProfileIMG != null)
                                        {
                                            <img class="media-object" src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(item.User.ProfileIMG))" alt="@item.User.FirstName @item.User.LastName" />
                                        }
                                        else
                                        {
                                            <img class="media-object" src="~/Image/DefaultProfile.jpg" alt="@item.User.FirstName @item.User.LastName" />
                                        }
                                        <div class="media-body">

                                            <h4 class="media-heading">@Html.DisplayFor(model => item.User.FirstName) @Html.DisplayFor(model => item.User.LastName)</h4>
                                            <p style="margin-left:3%;">@Html.DisplayFor(model => item.Content)</p>
                                        </div>
                                        <br />
                                    }
                                </div>
                            }
                        </div>
                </div>
            </div>
        </div>
    </section>





    <footer>
        <div class="social">

        </div>

    </footer>
</body>
</html>