IMDB/ViewModels/FavoriteActor.cs
using IMDB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IMDB.ViewModels
{
    public class FavoriteActor
    {
        public IEnumerable<Actor> Actors { get; set; }

        public UserFavoriteActor UserFavoriteActor { get; set; }

        public User User { get; set; }
    }
}

IMDB/ViewModels/FavoriteDirector.cs
using IMDB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IMDB.ViewModels
{
    public class FavoriteDirector
    {
        public IEnumerable<Director> Directors { get; set; }

        public UserFavoriteDirector UserFavoriteDirector { get; set; }

        public User User { get; set; }
    }
}

IMDB/Controllers/FavoriteController.cs
using IMDB.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMDB.Controllers
{
    public class FavoriteController : Controller
    {
        private DBContext db = new DBContext();
        // GET: Favorite

        [HttpGet]
        [AllowAnonymous]
        public ActionResult FavoriteActor()
        {
            var actors = db.Actors.ToList();

            FavoriteActor favActor = new FavoriteActor()
            {
                Actors = actors,
            };

            return View(favActor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FavoriteActor(FavoriteActor favActor)
        {
            int userId = (int)Session["UserId"];
            if (ModelState.IsValid)
            {
                
                favActor.User.UserID = userId;
                db.UserFavoriteActors.Add(favActor.UserFavoriteActor);
                db.SaveChanges();
                return RedirectToAction("Home");
            }
            var actors = db.Actors.ToList();
            favActor.Actors = actors;
            return View(favActor);
        }


        [HttpGet]
        [AllowAnonymous]
        public ActionResult FavoriteDirector()
        {
            var directors = db.Directors.ToList();

            FavoriteDirector favDirector = new FavoriteDirector()
            {
                Directors = directors,
            };

            return View(favDirector);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FavoriteDirector(FavoriteDirector favDirector)
        {
            int userId = (int)Session["UserId"];
            if (ModelState.IsValid)
            {

                favDirector.User.UserID = userId;
                db.UserFavoriteDirectors.Add(favDirector.UserFavoriteDirector);
                db.SaveChanges();
                return RedirectToAction("Home");
            }
            var directors = db.Directors.ToList();
            favDirector.Directors = directors;
            return View(favDirector);
        }

    }
}

IMDB/Views/Favorite/FavoriteActor.cshtml
@model IMDB.ViewModels.FavoriteDirector
@{
    ViewBag.Title = "Favorite Director";
}

<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/CreationForm.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/CreationForm.css" rel="stylesheet" />
</head>
<body>

    <div class="IMDB-image">
        <a href="@Url.Action(" Home", "Home" )">
            <img src="~/Image/IMDb Image.png" alt="IMDb logo" />
        </a>
    </div>

    <div class="creation-form">
        <h1 class="Header">Assign Movie to Actor</h1>

        @using (Html.BeginForm("FavoriteDirector", "Favorite", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
        @Html.AntiForgeryToken()

        <div class="text-line">
            @Html.LabelFor(text => text.UserFavoriteDirector.DirectorID, "Director Name")
            @Html.DropDownListFor(name => name.UserFavoriteDirector.DirectorID, new SelectList(Model.Directors, "ActorID", "FirstName"), "Select The Actor", new { @class = "list" })
            <span style="color:red">@Html.ValidationMessageFor(name => name.UserFavoriteDirector.ActorID)</span>
        </div>

        <div class="text-line">
            <input type="submit" value="Assign" class="button" aria-label="File browser example" />
            @Html.ActionLink("Back", "Home", new { @class = "Linkbutton" }, new { @id = "BackBtn" })
        </div>
        }
    </div>
</body>
</html>

IMDB/Views/Favorite/FavoriteDirector.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FavoriteDirector</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>